import std
import math

proc callback_proc (cb) then
    std.printval(1)
    std.printval("\n")
    cb()
    std.printval(2)
    std.printval("\n")
end

proc main () then
    let msg = "Hello, world!\n"
    std.printval(msg)
    msg = "Hello, test message!\n"
    builtin.printval(msg)


    callback_proc(proc cb() then std.printval("hello from callback\n") end)
    # 
    # for i = 0 to 10 then
    #     let z = i * 2
    #     printf("{}", z)
    # end
end