import std
import math

proc callback_proc (cb) then
    std.printlnval(1)
    # std.printval("\n")
    cb()
    std.printlnval(2)
    # std.printval("\n")
end

proc main () then
    let msg = "Hello, world!\n"
    std.printval(msg)
    msg = "Hello, test message!\n"
    builtin.printval(msg)


    callback_proc(proc cb() then std.printval("hello from callback\n") end)
    
    let test = 0

    for i = 0 to 10 then
        let z = i * 2

        test = test + z

        std.printlnval(z)
        
    end
    std.printlnval(test)

    std.printlnval(test + std.math.pi)
    let zo = 0.1f
    let zt = 0.2f
    std.printlnval(zo + zt)
end