import std
import math

proc euler(prev, depth) then
    std.printlnval(depth)
    if depth > 50 then
        std.printlnval("reached max")
        return prev
    end
    let ps = prev + 1/factorial(prev)
    let ret = euler(ps, depth + 1)
    return ret
end

proc factorial(num) then
    let p = 1
    for i = 1 to num then
        p = p * i
    end

    
    return p
end


proc main() then
    std.printlnval(std.math.e)
    std.printlnval(euler(0, 1))
end